[package]

# Semantic Versioning is used: https://semver.org/
version = "2.3.0"

# Description
category = "isaaclab"
readme  = "README.md"

title = "rnd_lab: RND STEP Sim-to-Real RL Extension."
author = "Ziqi Fan and fork contributors"
maintainer = "bounceonme"
description="RND STEP humanoid reinforcement-learning fork based on robot_lab and Isaac Lab."
repository = "https://github.com/bounceonme/rnd_lab.git"
keywords = ["extension", "rnd_lab", "robot_lab", "isaaclab", "rnd-step", "humanoid", "sim2real"]

[dependencies]
"isaaclab" = {}
"isaaclab_assets" = {}
"isaaclab_mimic" = {}
"isaaclab_rl" = {}
"isaaclab_tasks" = {}
# NOTE: Add additional dependencies here

[[python.module]]
name = "robot_lab"

[isaac_lab_settings]
# TODO: Uncomment and list any apt dependencies here.
#       If none, leave it commented out.
# apt_deps = ["example_package"]
# TODO: Uncomment and provide path to a ros_ws
#       with rosdeps to be installed. If none,
#       leave it commented out.
# ros_ws = "path/from/extension_root/to/ros_ws"
